name: azure
channels:
  - conda-forge
  - nodefaults
dependencies:
  - pip
  - python=3.11
  - ipykernel
  - click
  - pyyaml
  - pip:
    - azure-batch 
    - azure-storage-blob
    - azure-mgmt-resource
    - azure-identity
    - msrest
# pip install --no-deps -e . after cloning to install this package