name: azure
channels:
  - conda-forge
  - nodefaults
dependencies:
  - pip
  - python=3.8
  - ipykernel
  - click
  - pyyaml
  - autopep8
  - pip:
    - azure-batch #==11.0.0
    - azure-storage-blob #==12.9.0
    - azure-mgmt-resource #>=20.0.0
    - azure-identity #>=1.7.1
    - msrest #>=0.6.21
# pip install --no-deps -e . after cloning to install this package