location: eastus # the location of the batch account
pool_name: "{job_name}"
num_hosts: 1
vm_size: "standard_hb120rs_v2" # use any of the H series from https://learn.microsoft.com/en-us/azure/virtual-machines/sizes-hpc
study_copy_flags: "--recursive --preserve-symlinks --exclude-regex='.*outputs.*nc'"
setup_dirs_copy_flags: "--recursive --preserve-symlinks"
delete_after_mins: 240 # delete the job after this many minutes
mpi_command: 'printenv; echo "define mpi_command in job config yaml file";'
task_slots_per_node: 1
# translates to pkg_resources.resource_filename('dmsbatch', 'templates/<template_name>/a>
application_command_template: 'templates/{template_name}/application_command_template.sh' 
coordination_command_template: 'templates/{template_name}/coordination_command_template.sh'
job_start_command_template: 'templates/{template_name}/job_start_command_template.sh' 
pool_bicep_resource: 'templates/{template_name}/pool.bicep' 
pool_parameters_resource: 'templates/{template_name}/pool.parameters.json'
node_type: 'TargetDedicatedNodes' # 'TargetLowPriorityNodes'
autoscale_formula: 'templates/{template_name}/autoscale_formula.txt'
created_by: '' # this is the user who created the job
app_pkgs:
- name: batch_setup
- name: nfs
- name: schism_with_deps
- name: schimpy_with_deps
- name: baydeltaschism
- name: telegraf
- name: suxarray_with_deps