# Refer ./setup/baseConfig.yaml for full set of config parameters

allow-other: true

read-only: {read_only}

logging:
  type: syslog
  level: log_debug

components:
  - libfuse
  - file_cache
  - attr_cache
  - azstorage

libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240

file_cache:
  path: {mount_point}/.tmp{container_name}
  timeout-sec: 120
  max-size-mb: {cache_size_mb}

attr_cache:
  timeout-sec: 7200

azstorage:
  type: block
  account-name: {storage_account_name}
  account-key: {storage_account_key}
  endpoint: https://{storage_account_name}.blob.core.windows.net
  mode: key
  container: {container_name}