location: eastus # the location of the batch account
pool_name: "{job_name}"
num_hosts: 1
vm_size: "standard_hb120rs_v2" # use any of the H series from https://learn.microsoft.com/en-us/azure/virtual-machines/sizes-hpc
study_copy_flags: "--recursive --preserve-symlinks --exclude-regex='.*outputs.*nc'"
delete_after_mins: 240 # delete the job after this many minutes
mpi_command: 'printenv; echo "define mpi_command in job config yaml file";'
# translates to pkg_resources.resource_filename('dmsbatch', 'templates/<template_name>/a>
application_command_template: 'templates/{template_name}/application_command_template.sh' 
coordination_command_template: 'templates/{template_name}/coordination_command_template.sh'
job_start_command_template: 'templates/{template_name}/job_start_command_template.sh' 
pool_bicep_resource: 'templates/{template_name}/pool.bicep' 
pool_parameters_resource: 'templates/{template_name}/pool.parameters.json' 
created_by: '' # this is the user who created the job