{% set name = "dmsbatch" %}
{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev0') %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed -vv .
  noarch: python
  entry_points:
    - dmsbatch = dmsbatch.cli:main

requirements:
  host:
    - python
    - pip
    - setuptools >=45
    - wheel
    - setuptools_scm >=6.2
  run:
    - python
    - azure-batch >=11.0.0
    - azure-storage-blob >=2.1.0
    - azure-mgmt-resource >=18.0.0
    - azure-identity >=1.5.0

test:
  source_files:
    - tests
  requires:
    - pytest
    - pytest-cov
  #commands:
    #- pytest # not doing pytest because the integration tests require secrets
  imports:
   - dmsbatch
about:
  home: https://github.com/CADWRDeltaModeling/azure_dms_batch
  summary: Azure Batch for Delta Modeling Section
  license: MIT
  license_file: LICENSE
